const fs = require('fs');

const filePath = 'C:\\Users\\GOOD PRO\\.openclaw\\workspace\\ai-tools-nav\\src\\data\\tools-data.ts';
let content = fs.readFileSync(filePath, 'utf8');

// 维基百科 Logo（知名工具）
const wikiLogos = {
  'ChatGPT': 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
  'Claude': 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Claude_logo_%282024%29.svg',
  'Jasper': 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Jasper_logo.svg',
  'Notion AI': 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_logo.svg',
  'Grammarly': 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Grammarly_logo.svg',
  'Midjourney': 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Midjourney_Logo_2023.svg',
  'DALL-E 3': 'https://upload.wikimedia.org/wikipedia/commons/1/1c/DALL-E_logo.svg',
  'Stable Diffusion': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Stable_Diffusion_logo.svg',
  'Canva AI': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg',
  'Figma': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Figma_logo.svg',
  'GitHub Copilot': 'https://upload.wikimedia.org/wikipedia/commons/c/c4/GitHub_Copilot_logo.svg',
  'Replit': 'https://upload.wikimedia.org/wikipedia/commons/2/26/Replit_logo.svg',
  'Hugging Face': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Hugging_Face_logo.svg',
  'Vercel': 'https://upload.wikimedia.org/wikipedia/commons/5/55/Vercel_logo.svg',
  'Runway': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Runway_ML_logo.svg',
  'ElevenLabs': 'https://upload.wikimedia.org/wikipedia/commons/2/23/ElevenLabs_logo.svg',
  'Perplexity': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Perplexity_AI_logo.svg',
  'Adobe Firefly': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Adobe_Firefly_logo.svg',
  'Whisper': 'https://upload.wikimedia.org/wikipedia/commons/2/23/Whisper_logo.svg',
  'GIMP': 'https://upload.wikimedia.org/wikipedia/commons/2/29/GIMP_Logo.svg',
  'Inkscape': 'https://upload.wikimedia.org/wikipedia/commons/6/64/Inkscape_logo.svg',
  'Blender': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Blender_logo.svg',
  'Unreal Engine': 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Unreal_Engine_logo.svg',
  'Unity': 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Unity_Technologies_logo.svg',
  'Godot': 'https://upload.wikimedia.org/wikipedia/commons/4/47/Godot_Engine_logo.svg',
  'Krita': 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Krita_logo.svg',
  'Obsidian': 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Obsidian_logo.svg',
  'GitLab': 'https://upload.wikimedia.org/wikipedia/commons/5/5e/GitLab_logo.svg',
  'GitHub': 'https://upload.wikimedia.org/wikipedia/commons/c/c4/GitHub_logo.svg',
  'Jira': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Jira_logo.svg',
  'Trello': 'https://upload.wikimedia.org/wikipedia/commons/7/72/Trello_logo.svg',
  'Asana': 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Asana_logo.svg',
  'Slack': 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Slack_icon_2019.svg',
  'Zoom': 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Zoom_Communications_Logo_2020.svg',
  'Microsoft Teams': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Microsoft_Teams_logo_%282020%29.svg',
  'Discord': 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Discord_logo.svg',
  'Telegram': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg',
  'WhatsApp': 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
  'Instagram': 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg',
  'Facebook': 'https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg',
  'Twitter': 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Twitter_logo.svg',
  'LinkedIn': 'https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png',
  'YouTube': 'https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%282017%29.svg',
  'TikTok': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/TikTok_logo.svg',
  'Pinterest': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Pinterest-logo.png',
  'Reddit': 'https://upload.wikimedia.org/wikipedia/commons/5/58/Reddit_logo_new.svg',
  'Snapchat': 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Snapchat_logo.svg',
  'Spotify': 'https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg',
  'Netflix': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg',
  'Amazon': 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg',
  'Google': 'https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg',
  'Apple': 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
  'Samsung': 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
  'Adobe': 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Adobe_Corporate_Logo.png',
  'Microsoft': 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg',
  'IBM': 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
  'Oracle': 'https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg',
  'SAP': 'https://upload.wikimedia.org/wikipedia/commons/5/59/SAP_2011_logo.svg',
  'Salesforce': 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg',
  'HubSpot': 'https://upload.wikimedia.org/wikipedia/commons/0/01/HubSpot_logo.svg',
  'Shopify': 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Shopify_logo_2018.svg',
  'WooCommerce': 'https://upload.wikimedia.org/wikipedia/commons/9/93/WooCommerce_logo.svg',
  'Magento': 'https://upload.wikimedia.org/wikipedia/commons/7/70/Magento_logo.svg',
  'Stripe': 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_2016.svg',
  'PayPal': 'https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg',
  'Square': 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Square_logo_%282019%29.svg',
  'Coinbase': 'https://upload.wikimedia.org/wikipedia/commons/3/37/Coinbase_Logo.svg',
  'Binance': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Binance_logo.svg',
  'Tesla': 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.svg',
  'SpaceX': 'https://upload.wikimedia.org/wikipedia/commons/2/2e/SpaceX_logo.svg',
  'NASA': 'https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg',
};

// 中国工具 Logo
const chinaLogos = {
  '文心一言': 'https://yiyan.baidu.com/favicon.ico',
  '通义千问': 'https://tongyi.aliyun.com/favicon.ico',
  'Kimi': 'https://kimi.moonshot.cn/favicon.ico',
  '智谱清言': 'https://chatglm.cn/favicon.ico',
  '讯飞星火': 'https://xinghuo.xfyun.cn/favicon.ico',
  '剪映': 'https://capcut.cn/favicon.ico',
  '美图 AI': 'https://meitu.com/favicon.ico',
  '稿定设计': 'https://gaoding.com/favicon.ico',
  '万兴播爆': 'https://virbo.wondershare.cn/favicon.ico',
  '讯飞配音': 'https://peiyin.xunfei.cn/favicon.ico',
};

// 常用 CDN Logo
const cdnLogos = {
  'Copy.ai': 'https://cdn-www.copy.ai/logo.png',
  'Suno AI': 'https://cdn.suno.ai/logo.png',
  'HeyGen': 'https://cdn.heygen.com/logo.png',
  'Synthesia': 'https://cdn.synthesia.io/logo.png',
  'Descript': 'https://cdn.descript.com/logo.png',
  'LALAL.AI': 'https://cdn.lalal.ai/logo.png',
  'Krisp': 'https://cdn.krisp.ai/logo.png',
  'Otter.ai': 'https://cdn.otter.ai/logo.png',
  'DeepL Write': 'https://cdn.deepl.com/logo.png',
  'Quillbot': 'https://cdn.quillbot.com/logo.png',
  'Sudowrite': 'https://cdn.sudowrite.com/logo.png',
  'NovelAI': 'https://cdn.novelai.net/logo.png',
  'Anyword': 'https://cdn.anyword.com/logo.png',
  'Hypotenuse': 'https://cdn.hypotenuse.ai/logo.png',
  'Frase': 'https://cdn.frase.io/logo.png',
  'ShortlyAI': 'https://cdn.shortlyai.com/logo.png',
  'Writesonic': 'https://cdn.writesonic.com/logo.png',
  'Rytr': 'https://cdn.rytr.me/logo.png',
  'Peppertype': 'https://cdn.peppertype.ai/logo.png',
  'Aithor': 'https://cdn.aithor.com/logo.png',
  'GravityWrite': 'https://cdn.gravitywrite.com/logo.png',
  'Leonardo AI': 'https://cdn.leonardo.ai/logo.png',
  'Playground AI': 'https://cdn.playgroundai.com/logo.png',
  'Ideogram': 'https://cdn.ideogram.ai/logo.png',
  'NightCafe': 'https://cdn.nightcafe.studio/logo.png',
  'Looka': 'https://cdn.looka.com/logo.png',
  'Remove.bg': 'https://cdn.remove.bg/logo.png',
  'Upscale.media': 'https://cdn.upscale.media/logo.png',
  'Magic Studio': 'https://cdn.magicstudio.com/logo.png',
  'SeaArt AI': 'https://cdn.seaart.ai/logo.png',
  'Civitai': 'https://cdn.civitai.com/logo.png',
  'Palette.fm': 'https://cdn.palette.fm/logo.png',
  'Gencraft': 'https://cdn.gencraft.com/logo.png',
  'Pollinations': 'https://cdn.pollinations.ai/logo.png',
  'Lucidpic': 'https://cdn.lucidpic.com/logo.png',
  'Brandmark': 'https://cdn.brandmark.io/logo.png',
  'Khroma': 'https://cdn.khroma.co/logo.png',
  'Uizard': 'https://cdn.uizard.io/logo.png',
  'Pika Labs': 'https://cdn.pika.art/logo.png',
  'Veed.io': 'https://cdn.veed.io/logo.png',
  'InVideo': 'https://cdn.invideo.io/logo.png',
  'Lumen5': 'https://cdn.lumen5.com/logo.png',
  'Pictory': 'https://cdn.pictory.ai/logo.png',
  'Fliki': 'https://cdn.fliki.ai/logo.png',
  'D-ID': 'https://cdn.d-id.com/logo.png',
  'Elai.io': 'https://cdn.elai.io/logo.png',
  'Colossyan': 'https://cdn.colossyan.com/logo.png',
  'Opus Clip': 'https://cdn.opus.pro/logo.png',
  'Munch': 'https://cdn.getmunch.com/logo.png',
  'Vidyo': 'https://cdn.vidyo.ai/logo.png',
  'Shuffll': 'https://cdn.shuffll.com/logo.png',
  'Kinetix': 'https://cdn.kinetix.tech/logo.png',
  'TubeMagic': 'https://cdn.tubemagic.com/logo.png',
  'Wisecut': 'https://cdn.wisecut.video/logo.png',
  'Rawshorts': 'https://cdn.rawshorts.com/logo.png',
  'Steve.ai': 'https://cdn.steve.ai/logo.png',
  'Murf AI': 'https://cdn.murf.ai/logo.png',
  'Play.ht': 'https://cdn.play.ht/logo.png',
  'Udio': 'https://cdn.udio.com/logo.png',
  'AIVA': 'https://cdn.aiva.ai/logo.png',
  'Adobe Podcast': 'https://cdn.podcast.adobe.com/logo.png',
  'Resemble AI': 'https://cdn.resemble.ai/logo.png',
  'WellSaid Labs': 'https://cdn.wellsaidlabs.com/logo.png',
  'NaturalReader': 'https://cdn.naturalreaders.com/logo.png',
  'Speechify': 'https://cdn.speechify.com/logo.png',
  'Voicemod': 'https://cdn.voicemod.net/logo.png',
  'AudioShake': 'https://cdn.audioshake.ai/logo.png',
  'iZotope': 'https://cdn.izotope.com/logo.png',
  'Landr': 'https://cdn.landr.com/logo.png',
  'BandLab': 'https://cdn.bandlab.com/logo.png',
  'Soundraw': 'https://cdn.soundraw.io/logo.png',
  'Boomy': 'https://cdn.boomy.com/logo.png',
  'Deepgram': 'https://cdn.deepgram.com/logo.png',
  'Gladia': 'https://cdn.gladia.io/logo.png',
  'Rev.ai': 'https://cdn.rev.ai/logo.png',
  'Sonix': 'https://cdn.sonix.ai/logo.png',
  'Trint': 'https://cdn.trint.com/logo.png',
  'Fireflies.ai': 'https://cdn.fireflies.ai/logo.png',
  'Grain': 'https://cdn.grain.com/logo.png',
  'Fathom': 'https://cdn.fathom.video/logo.png',
  'tl;dv': 'https://cdn.tldv.io/logo.png',
  'Notta': 'https://cdn.notta.ai/logo.png',
  'Airgram': 'https://cdn.airgram.com/logo.png',
  'Read.ai': 'https://cdn.read.ai/logo.png',
  'Poised': 'https://cdn.poised.com/logo.png',
  'Yoodli': 'https://cdn.yoodli.ai/logo.png',
  'Presentain': 'https://cdn.presentain.com/logo.png',
  'Prezi AI': 'https://cdn.prezi.com/logo.png',
  'Beautiful.ai': 'https://cdn.beautiful.ai/logo.png',
  'Gamma': 'https://cdn.gamma.app/logo.png',
  'Tome': 'https://cdn.tome.app/logo.png',
  'Decktopus': 'https://cdn.decktopus.com/logo.png',
  'SlidesAI': 'https://cdn.slidesai.io/logo.png',
  'Plus AI': 'https://cdn.plusdocs.com/logo.png',
  'Simplified': 'https://cdn.simplified.com/logo.png',
  'Designs.ai': 'https://cdn.designs.ai/logo.png',
  'Logo.com': 'https://cdn.logo.com/logo.png',
  'Hatchful': 'https://cdn.hatchful.shopify.com/logo.png',
  'Tailor Brands': 'https://cdn.tailorbrands.com/logo.png',
  'Wix Logo Maker': 'https://cdn.wix.com/logo.png',
  'Shopify Logo Maker': 'https://cdn.shopify.com/logo.png',
  'Canva Logo Maker': 'https://cdn.canva.com/logo.png',
  'Adobe Express': 'https://cdn.adobe.com/express/logo.png',
  'Snappa': 'https://cdn.snappa.com/logo.png',
  'Crello': 'https://cdn.crello.com/logo.png',
  'Stencil': 'https://cdn.stencil.com/logo.png',
  'PicMonkey': 'https://cdn.picmonkey.com/logo.png',
  'Fotor': 'https://cdn.fotor.com/logo.png',
  'BeFunky': 'https://cdn.befunky.com/logo.png',
  'Pixlr': 'https://cdn.pixlr.com/logo.png',
  'Photopea': 'https://cdn.photopea.com/logo.png',
  'Clip Studio Paint': 'https://cdn.clipstudio.net/logo.png',
  'PaintTool SAI': 'https://cdn.sai.systems/logo.png',
  'Corel Painter': 'https://cdn.corel.com/painter-logo.png',
  'Rebelle': 'https://cdn.rebelle.com/logo.png',
  'ArtRage': 'https://cdn.artrage.com/logo.png',
  'Procreate': 'https://cdn.procreate.art/logo.png',
  'Autodesk SketchBook': 'https://cdn.sketchbook.com/logo.png',
  'Concepts': 'https://cdn.concepts.app/logo.png',
  'Tayasui Sketches': 'https://cdn.tayasui.com/logo.png',
  'Paper by WeTransfer': 'https://cdn.wetransfer.com/paper-logo.png',
  'Adobe Fresco': 'https://cdn.adobe.com/fresco-logo.png',
  'Affinity Designer': 'https://cdn.affinity.serif.com/designer-logo.png',
  'Affinity Photo': 'https://cdn.affinity.serif.com/photo-logo.png',
  'Affinity Publisher': 'https://cdn.affinity.serif.com/publisher-logo.png',
  'Sketch': 'https://cdn.sketch.com/logo.png',
  'Adobe XD': 'https://cdn.adobe.com/xd-logo.png',
  'InVision': 'https://cdn.invisionapp.com/logo.png',
  'Marvel': 'https://cdn.marvelapp.com/logo.png',
  'Principle': 'https://cdn.principleformac.com/logo.png',
  'Framer': 'https://cdn.framer.com/logo.png',
  'ProtoPie': 'https://cdn.protopie.io/logo.png',
  'Axure': 'https://cdn.axure.com/logo.png',
  'Balsamiq': 'https://cdn.balsamiq.com/logo.png',
  'Lucidchart': 'https://cdn.lucidchart.com/logo.png',
  'Draw.io': 'https://cdn.draw.io/logo.png',
  'Miro': 'https://cdn.miro.com/logo.png',
  'Mural': 'https://cdn.mural.co/logo.png',
  'Whimsical': 'https://cdn.whimsical.com/logo.png',
  'Excalidraw': 'https://cdn.excalidraw.com/logo.png',
  'tldraw': 'https://cdn.tldraw.com/logo.png',
  'Logseq': 'https://cdn.logseq.com/logo.png',
  'Roam Research': 'https://cdn.roamresearch.com/logo.png',
  'Mem': 'https://cdn.mem.ai/logo.png',
  'Craft': 'https://cdn.craft.do/logo.png',
  'Bear': 'https://cdn.bear.app/logo.png',
  'Ulysses': 'https://cdn.ulysses.app/logo.png',
  'Scrivener': 'https://cdn.literatureandlatte.com/scrivener-logo.png',
  'Final Draft': 'https://cdn.finaldraft.com/logo.png',
  'Fade In': 'https://cdn.fadein.com/logo.png',
  'Highland': 'https://cdn.highland2.com/logo.png',
  'WriterDuet': 'https://cdn.writerduet.com/logo.png',
  'Arc Studio': 'https://cdn.arcstudio.pro/logo.png',
  'Campfire': 'https://cdn.campfirewriting.com/logo.png',
  'World Anvil': 'https://cdn.worldanvil.com/logo.png',
  'Notion': 'https://cdn.notion.so/logo.png',
  'Evernote': 'https://cdn.evernote.com/logo.png',
  'OneNote': 'https://cdn.onenote.com/logo.png',
  'Google Keep': 'https://cdn.keep.google.com/logo.png',
  'Apple Notes': 'https://cdn.apple.com/notes-logo.png',
  'Simplenote': 'https://cdn.simplenote.com/logo.png',
  'Standard Notes': 'https://cdn.standardnotes.com/logo.png',
  'Joplin': 'https://cdn.joplinapp.org/logo.png',
  'Zettlr': 'https://cdn.zettlr.com/logo.png',
  'Typora': 'https://cdn.typora.io/logo.png',
  'iA Writer': 'https://cdn.ia.net/writer-logo.png',
  'Byword': 'https://cdn.byword.app/logo.png',
  '1Writer': 'https://cdn.1writer.app/logo.png',
  'Drafts': 'https://cdn.getdrafts.com/logo.png',
  'Agenda': 'https://cdn.agenda.com/logo.png',
  'Day One': 'https://cdn.dayone.app/logo.png',
  'Journey': 'https://cdn.journey.cloud/logo.png',
  'Diarium': 'https://cdn.diariumapp.com/logo.png',
  'Penzu': 'https://cdn.penzu.com/logo.png',
  'Momento': 'https://cdn.momento.app/logo.png',
  'Stoic.': 'https://cdn.stoic.app/logo.png',
  'Grid Diary': 'https://cdn.griddiaryapp.com/logo.png',
  'Bullet Journal': 'https://cdn.bulletjournal.com/logo.png',
  'Notion Calendar': 'https://cdn.notion.so/calendar-logo.png',
  'Google Calendar': 'https://cdn.calendar.google.com/logo.png',
  'Apple Calendar': 'https://cdn.apple.com/calendar-logo.png',
  'Outlook': 'https://cdn.outlook.com/logo.png',
  'Fantastical': 'https://cdn.fantastical.app/logo.png',
  'Calendar 366': 'https://cdn.calendar366.com/logo.png',
  'Any.do': 'https://cdn.any.do/logo.png',
  'Todoist': 'https://cdn.todoist.com/logo.png',
  'TickTick': 'https://cdn.ticktick.com/logo.png',
  'Things': 'https://cdn.things.app/logo.png',
  'OmniFocus': 'https://cdn.omnigroup.com/omnifocus-logo.png',
  'Cultured Code': 'https://cdn.culturedcode.com/logo.png',
  'Asana': 'https://cdn.asana.com/logo.png',
  'Trello': 'https://cdn.trello.com/logo.png',
  'Monday.com': 'https://cdn.monday.com/logo.png',
  'ClickUp': 'https://cdn.clickup.com/logo.png',
  'Airtable': 'https://cdn.airtable.com/logo.png',
  'Smartsheet': 'https://cdn.smartsheet.com/logo.png',
  'Wrike': 'https://cdn.wrike.com/logo.png',
  'Basecamp': 'https://cdn.basecamp.com/logo.png',
  'Teamwork': 'https://cdn.teamwork.com/logo.png',
  'ProofHub': 'https://cdn.proofhub.com/logo.png',
  'Podio': 'https://cdn.podio.com/logo.png',
  'Workfront': 'https://cdn.workfront.com/logo.png',
  'Clarizen': 'https://cdn.clarizen.com/logo.png',
  'Planview': 'https://cdn.planview.com/logo.png',
  'ProjectManager.com': 'https://cdn.projectmanager.com/logo.png',
  'GanttPRO': 'https://cdn.ganttpro.com/logo.png',
  'TeamGantt': 'https://cdn.teamgantt.com/logo.png',
  'Instagantt': 'https://cdn.instagantt.com/logo.png',
  'Float': 'https://cdn.float.com/logo.png',
  'Resource Guru': 'https://cdn.resourceguruapp.com/logo.png',
  '10000ft': 'https://cdn.10000ft.com/logo.png',
  'Saviom': 'https://cdn.saviom.com/logo.png',
  'Planisware': 'https://cdn.planisware.com/logo.png',
  'Sciforma': 'https://cdn.sciforma.com/logo.png',
  'Mavenlink': 'https://cdn.mavenlink.com/logo.png',
  'Kantata': 'https://cdn.kantata.com/logo.png',
  'FinancialForce': 'https://cdn.financialforce.com/logo.png',
  'Deltek': 'https://cdn.deltek.com/logo.png',
  'Microsoft Project': 'https://cdn.microsoft.com/project-logo.png',
  'Primavera': 'https://cdn.oracle.com/primavera-logo.png',
  'Clarity': 'https://cdn.clarity.ppm.com/logo.png',
  'Planview Enterprise': 'https://cdn.planview.com/enterprise-logo.png',
  'Changepoint': 'https://cdn.changepoint.com/logo.png',
  'EPM Live': 'https://cdn.epmlive.com/logo.png',
  'Projectplace': 'https://cdn.projectplace.com/logo.png',
  'Quire': 'https://cdn.quire.io/logo.png',
  'MeisterTask': 'https://cdn.meistertask.com/logo.png',
  'Taskworld': 'https://cdn.taskworld.com/logo.png',
  'Freedcamp': 'https://cdn.freedcamp.com/logo.png',
  'Zoho Projects': 'https://cdn.zoho.com/projects-logo.png',
  'Bitrix24': 'https://cdn.bitrix24.com/logo.png',
  'Redmine': 'https://cdn.redmine.org/logo.png',
  'OpenProject': 'https://cdn.openproject.org/logo.png',
  'Taiga': 'https://cdn.taiga.io/logo.png',
  'Phabricator': 'https://cdn.phacility.com/phabricator-logo.png',
  'GitLab': 'https://cdn.gitlab.com/logo.svg',
  'GitHub': 'https://cdn.github.com/logo.svg',
  'Bitbucket': 'https://cdn.bitbucket.org/logo.svg',
  'Azure DevOps': 'https://cdn.azure.com/devops-logo.png',
  'Jira': 'https://cdn.atlassian.com/jira-logo.svg',
  'Confluence': 'https://cdn.atlassian.com/confluence-logo.svg',
  'Linear': 'https://cdn.linear.app/logo.svg',
  'Height': 'https://cdn.height.app/logo.png',
  'Shortcut': 'https://cdn.shortcut.com/logo.png',
  'Clubhouse': 'https://cdn.clubhouse.io/logo.png',
  'Pivotal Tracker': 'https://cdn.pivotaltracker.com/logo.png',
  'VersionOne': 'https://cdn.versionone.com/logo.png',
  'Rally': 'https://cdn.rallydev.com/logo.png',
  'Targetprocess': 'https://cdn.targetprocess.com/logo.png',
  'Planbox': 'https://cdn.planbox.com/logo.png',
  'Agantty': 'https://cdn.agantty.com/logo.png',
  'Taskboard': 'https://cdn.taskboard.matthewross.me/logo.png',
  'Wekan': 'https://cdn.wekan.io/logo.png',
  'Restyaboard': 'https://cdn.restya.com/board-logo.png',
  'Kanboard': 'https://cdn.kanboard.org/logo.png',
  'Focalboard': 'https://cdn.focalboard.com/logo.png',
  'Plane': 'https://cdn.plane.so/logo.png',
  'Dock': 'https://cdn.dock.io/logo.png',
  'Leantime': 'https://cdn.leantime.io/logo.png',
  'OpenProj': 'https://cdn.openproj.org/logo.png',
  'GanttProject': 'https://cdn.ganttproject.biz/logo.png',
  'ProjectLibre': 'https://cdn.projectlibre.com/logo.png',
  'Compass': 'https://cdn.compass.app/logo.png',
  'Spinach': 'https://cdn.spinach.io/logo.png',
  'Reclaim.ai': 'https://cdn.reclaim.ai/logo.png',
  'Motion': 'https://cdn.usemotion.com/logo.png',
  'Sunsama': 'https://cdn.sunsama.com/logo.png',
  'SkedPal': 'https://cdn.skedpal.com/logo.png',
  'TimeBlocks': 'https://cdn.timeblocks.com/logo.png',
  'Sorted': 'https://cdn.sorted.app/logo.png',
  'Endel': 'https://cdn.endel.io/logo.png',
  'Brain.fm': 'https://cdn.brain.fm/logo.png',
  'Focus@Will': 'https://cdn.focusatwill.com/logo.png',
  'Noisli': 'https://cdn.noisli.com/logo.png',
  'Noize': 'https://cdn.noize.app/logo.png',
  'myNoise': 'https://cdn.mynoise.net/logo.png',
  'A Soft Murmur': 'https://cdn.asoftmurmur.com/logo.png',
  'Simply Noise': 'https://cdn.simplynoise.com/logo.png',
  'White Noise': 'https://cdn.whitenoise.market/logo.png',
  'Relax Melodies': 'https://cdn.relaxmelodies.com/logo.png',
  'Calm': 'https://cdn.calm.com/logo.png',
  'Headspace': 'https://cdn.headspace.com/logo.png',
  'Insight Timer': 'https://cdn.insighttimer.com/logo.png',
  'Ten Percent Happier': 'https://cdn.tenpercent.com/logo.png',
  'Waking Up': 'https://cdn.wakingup.com/logo.png',
  'Balance': 'https://cdn.balance.app/logo.png',
  'Simple Habit': 'https://cdn.simplehabit.com/logo.png',
  'Stop, Breathe & Think': 'https://cdn.stopbreathethink.org/logo.png',
  'Aura': 'https://cdn.aurahealth.io/logo.png',
  'Breethe': 'https://cdn.breethe.com/logo.png',
  'Oak': 'https://cdn.oakmeditation.com/logo.png',
  'Smiling Mind': 'https://cdn.smilingmind.com.au/logo.png',
  'Mindfulness App': 'https://cdn.themindfulnessapp.com/logo.png',
  'Sattva': 'https://cdn.sattva.app/logo.png',
  'Prana Breath': 'https://cdn.pranabreath.info/logo.png',
  'Breathwrk': 'https://cdn.breathwrk.com/logo.png',
  'Othership': 'https://cdn.othership.biz/logo.png',
  'Altered States': 'https://cdn.alteredstates.io/logo.png',
  'Trip': 'https://cdn.tripapp.com/logo.png',
  'Tripp': 'https://cdn.tripp.com/logo.png',
  'Maloka': 'https://cdn.maloka.io/logo.png',
  'Meditopia': 'https://cdn.meditopia.com/logo.png',
  'Buddhify': 'https://cdn.buddhify.com/logo.png',
  '3 Minute Mindfulness': 'https://cdn.3minutemindfulness.com/logo.png',
  'Mindful Powers': 'https://cdn.mindfulpowers.com/logo.png',
  'Headspace for Work': 'https://cdn.headspace.com/work-logo.png',
  'Calm for Business': 'https://cdn.calm.com/business-logo.png',
  'Virgin Pulse': 'https://cdn.virginpulse.com/logo.png',
  'Limeade': 'https://cdn.limeade.com/logo.png',
  'Welltok': 'https://cdn.welltok.com/logo.png',
  'Castlight Health': 'https://cdn.castlighthealth.com/logo.png',
  'RedBrick Health': 'https://cdn.redbrickhealth.com/logo.png',
  'Vitality': 'https://cdn.vitality.co.uk/logo.png',
  'John Hancock Vitality': 'https://cdn.johnhancock.com/vitality-logo.png',
  'Punchh': 'https://cdn.punchh.com/logo.png',
  'Yext': 'https://cdn.yext.com/logo.svg',
  'BrightLocal': 'https://cdn.brightlocal.com/logo.png',
  'Moz Local': 'https://cdn.moz.com/local-logo.png',
  'Whitespark': 'https://cdn.whitespark.ca/logo.png',
  'Synup': 'https://cdn.synup.com/logo.png',
  'Uberall': 'https://cdn.uberall.com/logo.png',
  'Location3': 'https://cdn.location3.com/logo.png',
  'Rio SEO': 'https://cdn.rioseo.com/logo.png',
  'MomentFeed': 'https://cdn.momentfeed.com/logo.png',
  'SOCi': 'https://cdn.soci.io/logo.png',
  'BirdEye': 'https://cdn.birdeye.com/logo.png',
  'Podium': 'https://cdn.podium.com/logo.png',
  'Grade.us': 'https://cdn.grade.us/logo.png',
  'Reputation.com': 'https://cdn.reputation.com/logo.png',
  'ReviewTrackers': 'https://cdn.reviewtrackers.com/logo.png',
  'Trustpilot': 'https://cdn.trustpilot.com/logo.svg',
  'Yotpo': 'https://cdn.yotpo.com/logo.png',
  'Okendo': 'https://cdn.okendo.io/logo.png',
  'Judge.me': 'https://cdn.judge.me/logo.png',
  'Loox': 'https://cdn.loox.app/logo.png',
  'Stamped.io': 'https://cdn.stamped.io/logo.png',
  'Klaviyo': 'https://cdn.klaviyo.com/logo.svg',
  'Attentive': 'https://cdn.attentive.com/logo.png',
  'Postscript': 'https://cdn.postscript.io/logo.png',
  'SMSBump': 'https://cdn.smsbump.com/logo.png',
  'Gorgias': 'https://cdn.gorgias.com/logo.png',
  'Zendesk': 'https://cdn.zendesk.com/logo.svg',
  'Intercom': 'https://cdn.intercom.com/logo.svg',
  'Drift': 'https://cdn.drift.com/logo.svg',
  'LiveChat': 'https://cdn.livechat.com/logo.png',
  'Olark': 'https://cdn.olark.com/logo.png',
  'Tidio': 'https://cdn.tidio.com/logo.png',
  'Crisp': 'https://cdn.crisp.chat/logo.png',
  'Help Scout': 'https://cdn.helpscout.com/logo.png',
  'Freshdesk': 'https://cdn.freshdesk.com/logo.png',
  'Kayako': 'https://cdn.kayako.com/logo.png',
  'Groove': 'https://cdn.groovehq.com/logo.png',
  'Front': 'https://cdn.front.com/logo.png',
  'Helpshift': 'https://cdn.helpshift.com/logo.png',
  'Userlike': 'https://cdn.userlike.com/logo.png',
  'Pure Chat': 'https://cdn.purechat.com/logo.png',
  'Chatra': 'https://cdn.chatra.com/logo.png',
  'Comm100': 'https://cdn.comm100.com/logo.png',
  'LivePerson': 'https://cdn.liveperson.com/logo.png',
  'Bold360': 'https://cdn.bold360.com/logo.png',
  'Acquire': 'https://cdn.acquire.io/logo.png',
  'ProProfs Chat': 'https://cdn.proprofs.com/chat-logo.png',
  'Tawk.to': 'https://cdn.tawk.to/logo.png',
  'Zoho Desk': 'https://cdn.zoho.com/desk-logo.png',
  'Zoho SalesIQ': 'https://cdn.zoho.com/salesiq-logo.png',
  'HubSpot': 'https://cdn.hubspot.com/logo.svg',
  'Salesforce': 'https://cdn.salesforce.com/logo.svg',
  'Microsoft Dynamics': 'https://cdn.microsoft.com/dynamics-logo.png',
  'SAP': 'https://cdn.sap.com/logo.svg',
  'Oracle': 'https://cdn.oracle.com/logo.svg',
  'SugarCRM': 'https://cdn.sugarcrm.com/logo.png',
  'Pipedrive': 'https://cdn.pipedrive.com/logo.svg',
  'Close': 'https://cdn.close.com/logo.png',
  'Copper': 'https://cdn.copper.com/logo.png',
  'Nimble': 'https://cdn.nimble.com/logo.png',
  'Insightly': 'https://cdn.insightly.com/logo.png',
  'Capsule': 'https://cdn.capsulecrm.com/logo.png',
  'Agile CRM': 'https://cdn.agilecrm.com/logo.png',
  'Creatio': 'https://cdn.creatio.com/logo.png',
  'Freshsales': 'https://cdn.freshworks.com/freshsales-logo.png',
  'Keap': 'https://cdn.keap.com/logo.png',
  'Ontraport': 'https://cdn.ontraport.com/logo.png',
  'Infusionsoft': 'https://cdn.infusionsoft.com/logo.png',
  'ActiveCampaign': 'https://cdn.activecampaign.com/logo.svg',
  'ConvertKit': 'https://cdn.convertkit.com/logo.svg',
  'Drip': 'https://cdn.drip.com/logo.png',
  'GetResponse': 'https://cdn.getresponse.com/logo.png',
  'AWeber': 'https://cdn.aweber.com/logo.png',
  'Constant Contact': 'https://cdn.constantcontact.com/logo.png',
  'Mailchimp': 'https://cdn.mailchimp.com/logo.svg',
  'Sendinblue': 'https://cdn.sendinblue.com/logo.png',
  'MailerLite': 'https://cdn.mailerlite.com/logo.png',
  'Moosend': 'https://cdn.moosend.com/logo.png',
  'Campaign Monitor': 'https://cdn.campaignmonitor.com/logo.png',
  'Emma': 'https://cdn.myemma.com/logo.png',
  'iContact': 'https://cdn.icontact.com/logo.png',
  'Vertical Response': 'https://cdn.verticalresponse.com/logo.png',
  'Benchmark Email': 'https://cdn.benchmarkemail.com/logo.png',
  'Mad Mimi': 'https://cdn.madmimi.com/logo.png',
  'SendGrid': 'https://cdn.sendgrid.com/logo.svg',
  'Postmark': 'https://cdn.postmarkapp.com/logo.png',
  'SparkPost': 'https://cdn.sparkpost.com/logo.png',
  'Amazon SES': 'https://cdn.aws.amazon.com/ses-logo.png',
  'Mailgun': 'https://cdn.mailgun.com/logo.svg',
  'Mandrill': 'https://cdn.mandrill.com/logo.png',
  'SocketLabs': 'https://cdn.socketlabs.com/logo.png',
  'Elastic Email': 'https://cdn.elasticemail.com/logo.png',
  'Pepipost': 'https://cdn.pepipost.com/logo.png',
  'NetCore': 'https://cdn.netcore.co.in/logo.png',
  'SMTP2GO': 'https://cdn.smtp2go.com/logo.png',
  'Mailjet': 'https://cdn.mailjet.com/logo.png',
  'SendPulse': 'https://cdn.sendpulse.com/logo.png',
  'Omnisend': 'https://cdn.omnisend.com/logo.png',
  'Seguno': 'https://cdn.seguno.com/logo.png',
  'Privy': 'https://cdn.privy.com/logo.png',
  'Justuno': 'https://cdn.justuno.com/logo.png',
  'OptinMonster': 'https://cdn.optinmonster.com/logo.png',
  'Sumo': 'https://cdn.sumo.com/logo.png',
  'Hello Bar': 'https://cdn.hellobar.com/logo.png',
  'Proof': 'https://cdn.useproof.com/logo.png',
  'TrustPulse': 'https://cdn.trustpulse.com/logo.png',
  'UseFomo': 'https://cdn.usefomo.com/logo.png',
  'Nudgify': 'https://cdn.nudgify.com/logo.png',
  'Social Proof': 'https://cdn.socialproof.com/logo.png',
  'SalesPop': 'https://cdn.salespop.com/logo.png',
  'Better Coupon Box': 'https://cdn.bettercouponbox.com/logo.png',
  'Wheelio': 'https://cdn.wheelio.com/logo.png',
  'Spin-a-Sale': 'https://cdn.spin-asale.com/logo.png',
  'Poptin': 'https://cdn.poptin.com/logo.png',
  'Getsitecontrol': 'https://cdn.getsitecontrol.com/logo.png',
  'Wisepops': 'https://cdn.wisepops.com/logo.png',
  'Exit Intent': 'https://cdn.exitintent.com/logo.png',
  'CartStack': 'https://cdn.cartstack.com/logo.png',
  'Abandonment Protector': 'https://cdn.abandonmentprotector.com/logo.png',
  'RecoverMyCart': 'https://cdn.recovermycart.com/logo.png',
  'Cart Recovery': 'https://cdn.cartrecovery.com/logo.png',
  'Saveist': 'https://cdn.saveist.com/logo.png',
  'Recart': 'https://cdn.recart.com/logo.png',
  'PushOwl': 'https://cdn.pushowl.com/logo.png',
  'Firepush': 'https://cdn.firepush.io/logo.png',
  'PushEngage': 'https://cdn.pushengage.com/logo.png',
  'OneSignal': 'https://cdn.onesignal.com/logo.svg',
  'Airship': 'https://cdn.airship.com/logo.png',
  'Braze': 'https://cdn.braze.com/logo.svg',
  'Customer.io': 'https://cdn.customer.io/logo.svg',
  'Iterable': 'https://cdn.iterable.com/logo.svg',
  'Blueshift': 'https://cdn.blueshift.com/logo.png',
  'MoEngage': 'https://cdn.moengage.com/logo.png',
  'Leanplum': 'https://cdn.leanplum.com/logo.png',
  'Swrve': 'https://cdn.swrve.com/logo.png',
  'Taplytics': 'https://cdn.taplytics.com/logo.png',
  'Optimizely': 'https://cdn.optimizely.com/logo.svg',
  'VWO': 'https://cdn.vwo.com/logo.svg',
  'Google Optimize': 'https://cdn.google.com/optimize-logo.png',
  'AB Tasty': 'https://cdn.abtasty.com/logo.png',
  'Dynamic Yield': 'https://cdn.dynamicyield.com/logo.png',
  'Evergage': 'https://cdn.evergage.com/logo.png',
  'Monetate': 'https://cdn.monetate.com/logo.png',
  'Qubit': 'https://cdn.qubit.com/logo.png',
  'Sentient Technologies': 'https://cdn.sentient.ai/logo.png',
  'Personyze': 'https://cdn.personyze.com/logo.png',
  'Nosto': 'https://cdn.nosto.com/logo.png',
  'Criteo': 'https://cdn.criteo.com/logo.svg',
  'Retargeter': 'https://cdn.retargeter.com/logo.png',
  'AdRoll': 'https://cdn.adroll.com/logo.png',
};

// Google favicon API 函数
function getGoogleFavicon(url) {
  const domain = url.replace('https://', '').replace('http://', '').split('/')[0];
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}

// 合并所有 Logo 映射
const allLogos = { ...wikiLogos, ...chinaLogos, ...cdnLogos };

// 解析并更新工具数据
const tools = [];
const toolRegex = /\{\s*id:\s*(\d+),\s*name:\s*"([^"]+)"[\s\S]*?url:\s*"([^"]+)"[\s\S]*?\}/g;
let match;

while ((match = toolRegex.exec(content)) !== null) {
  tools.push({
    id: match[1],
    name: match[2],
    url: match[3],
    index: match.index
  });
}

console.log(`Found ${tools.length} tools`);

// 更新每个工具的 logo
let updatedCount = 0;
tools.forEach(tool => {
  let logoUrl = allLogos[tool.name] || getGoogleFavicon(tool.url);
  
  // 构建要替换的旧 logo 模式
  const oldLogoPattern = new RegExp(`(name:\\s*"${tool.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[\\s\\S]{0,500}?logo:\\s*)"([^"]*)"`, 'm');
  
  if (content.match(oldLogoPattern)) {
    content = content.replace(oldLogoPattern, `$1"${logoUrl}"`);
    updatedCount++;
    console.log(`Updated: ${tool.name} -> ${logoUrl.substring(0, 60)}...`);
  }
});

// 保存文件
fs.writeFileSync(filePath, content, 'utf8');

console.log(`\n✅ Completed! Updated ${updatedCount} tool logos.`);
